# Generated by Django 3.2.9 on 2021-12-07 12:15

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=20)),
                ('grado', models.CharField(choices=[('1', 'Primero basico'), ('2', 'Segundo basico'), ('3', 'Tercero basico'), ('4', 'Cuarto basico'), ('5', 'Quinto basico'), ('6', 'Sexto basico'), ('7', 'Septimo basico'), ('8', 'Octavo basico'), ('I', 'Primero medio'), ('II', 'Segundo medio'), ('III', 'Tercero medio'), ('IV', 'Cuarto medio'), ('PDT', 'PDT')], max_length=12)),
                ('asignatura_Basica', models.CharField(choices=[('N', 'No'), ('M', 'Matemáticas '), ('C', 'Ciencias Naturales '), ('L', 'Lenguaje y comunicación '), ('H', 'Historia, Geografía y Ciencias Sociales '), ('I', 'Ingles'), ('O', 'Otros')], default='N', max_length=1)),
                ('asignatura_Media', models.CharField(choices=[('N', 'No'), ('Z', 'Matemáticas '), ('C', 'Matemáticas avanzadas'), ('L', 'Lenguaje y comunicación '), ('H', 'Historia, Geografía y Ciencias Sociales '), ('F', 'Física '), ('E', 'Física avanzada '), ('Q', 'Química '), ('S', 'Química avanzada'), ('B', 'Biología '), ('A', 'Biología avanzada'), ('I', 'Ingles'), ('O', 'Otros')], default='N', max_length=1)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='images/Fondo.png', upload_to='images/')),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
